import pandas as pd

df = pd.read_csv("final_w_supplemental.csv")

jasons_list =  ['american museum of natural history',
 'arcadia university',
 'argonne national laboratory',
 'arizona state university',
 'bay area environmental research institute',
 'brookhaven national laboratory',
 'california institute of technology',
 'california state university, san bernadino',
 'carnegie-mellon university',
 'cedars-sinai medical center',
 'clemson university',
 'college of charleston',
 'colorado school of mines',
 'columbia university',
 'cornell university',
 'creighton university',
 'dearborn center for math, science, and technology',
 'duke university',
 'emory university',
 'eth zurich',
 'eureka scientific, inc.',
 'fermilab',
 'florida international university',
 'florida state university',
 'george washington university',
 'georgia institute of technology',
 'great plains network',
 'harvard medical school',
 'icahn school of medicine at mount sinai',
 'illinois institute of technology',
 'indiana university',
 'internet2',
 'jefferson lab',
 'johns hopkins university',
 'kansas state university',
 'kennesaw state university',
 'lancaster university',
 'louisiana state university',
 'loyola university chicago',
 'lsu school of public health',
 'massachusetts institute of technology',
 'memorial sloan kettering cancer center',
 'michigan state university',
 'national institute of allergy and infectious diseases',
 'national oceanic and atmospheric administration',
 'new jersey institute of technology',
 'new mexico state university',
 'niaid/nih',
 'noir lab',
 'north carolina state university',
 'northeastern university',
 'open science grid',
 'oregon health & science university',
 'osg',
 'pennsylvania state university',
 'planetary science institute',
 'portland state university',
 'rensselaer polytechnic institute',
 'rice university',
 'rochester institute of technology',
 'rutgers, the state university of new jersey',
 'stanford university',
 'state university of new york at stony brook',
 'steadman philippon research institute',
 'suny upstate medical university',
 'syracuse university',
 'the college of new jersey',
 'the university of alabama at birmingham',
 'united states department of agriculture',
 'university of arizona',
 'university of arkansas',
 'university of arkansas at little rock',
 'university of california, berkeley',
 'university of california, davis',
 'university of california, irvine',
 'university of california, merced',
 'university of california, san diego',
 'university of central florida',
 'university of chicago',
 'university of colorado anschutz medical campus',
 'university of colorado boulder',
 'university of colorado denver',
 'university of connecticut',
 'university of hawaii at manoa',
 'university of illinois urbana-champaign',
 'university of iowa',
 'university of massachusetts lowell',
 'university of michigan',
 'university of missouri',
 'university of montana',
 'university of nebraska-lincoln',
 'university of new mexico',
 'university of oregon',
 'university of pennsylvania',
 'university of pittsburgh',
 'university of puerto rico - mayaguez',
 'university of rochester',
 'university of south carolina',
 'university of south dakota',
 'university of southern california',
 'university of texas at arlington',
 'university of texas at austin',
 'university of utah',
 'university of wisconsin-madison',
 'utah state university',
 'villanova university',
 'virginia tech university',
 'wayne state university',
 'wichita state university']

def in_list(x):
    return x['Institution Name'].lower() in jasons_list

print(f"Lenght of list: {len(jasons_list)}")

df["Benefited From"] = df.apply(in_list, axis=1)

df.to_csv("final_w_supplemental_w_benefitted.csv", index=False)

print(f"Number that benefitted: {df['Benefited From'].sum()}")